version: '3'


services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: test_wagtail

    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
    ports:
      - '8000:8000'
    depends_on:
      - redis
  redis:
    image: redis:6.2.12-alpine
    restart: always
    volumes:
      - redisdata:/data

volumes:
  redisdata:


